version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.12

    steps:
      - checkout

      - python/install-packages:
          pkg-manager: pip

      - run:
          name: Set PYTHONPATH
          command: echo 'export PYTHONPATH=read_resume/src' >> $BASH_ENV

      - run:
          name: Run tests
          command: |
            source $BASH_ENV
            pytest read_resume/tests

workflows:
  sample:
    jobs:
      - build-and-test
